services:
  - type: web
    name: n8n
    runtime: node
    buildCommand: npm install
    startCommand: npm run start
    env: node
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "admin" # Change this
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "password" # Change this
